// src/features/stagiaires/mock.ts
import { Stagiaire } from "@/types/stagiaire";

export const mockStagiaires: Stagiaire[] = [
  {
    id: 1,
    name: "Sara El Amrani",
    email: "sara.elamrani@emi.ac.ma",
    telephone: "+212 6 71 23 45 67",
    linkedin: "linkedin.com/in/sara-elamrani",
    github: "github.com/sara-elamrani",
    bio: "Étudiante en Génie Informatique, passionnée par le développement web full-stack et l'architecture logicielle.",
    ecole: "École Mohammadia d'Ingénieurs",
    filiere: "Génie Informatique",
    typeStage: "PFE",
    departement: "Systèmes d'Information",
    encadrantId: 1,
    encadrantName: "Karima Alaoui",
    dateDebut: "01 sept. 24",
    dateFin: "01 mars 25",
    avancement: 72,
    statut: "En cours",
    rapportStatut: "En attente",
    rapportFichierNom: "rapport-stage-sara-elamrani.pdf", // NOUVEAU
    rapportDateDepot: "03 févr. 2025",                      // NOUVEAU
    compteActif: true,
  },
  {
    id: 2,
    name: "Yassine Benali",
    email: "y.benali@insea.ac.ma",
    telephone: "06 22 33 44 55",
    linkedin: "linkedin.com/in/yassine-benali",
    github: "github.com/yassine-benali",
    bio: "Étudiant en Statistiques et Informatique Décisionnelle, orienté machine learning.",
    ecole: "INSEA",
    filiere: "Statistiques et Informatique Décisionnelle",
    typeStage: "PFE",
    departement: "Data & Analytics",
    encadrantId: 2,
    encadrantName: "Youssef Benali",
    dateDebut: "01 oct. 24",
    dateFin: "01 avr. 25",
    avancement: 58,
    statut: "En cours",
    rapportStatut: "Non déposé",
    compteActif: true,
  },
  {
    id: 3,
    name: "Imane Zouak",
    email: "i.zouak@encg.ac.ma",
    telephone: "06 33 44 55 66",
    linkedin: "linkedin.com/in/imane-zouak",
    bio: "Étudiante en Finance d'Entreprise à l'ENCG Casablanca.",
    ecole: "ENCG Casablanca",
    filiere: "Finance d'Entreprise",
    typeStage: "PFA",
    departement: "Finance",
    encadrantId: 3,
    encadrantName: "Nadia Chraibi",
    dateDebut: "01 nov. 24",
    dateFin: "01 mars 25",
    avancement: 45,
    statut: "En cours",
    rapportStatut: "Non déposé",
    compteActif: true,
  },
  {
    id: 4,
    name: "Adam Cherkaoui",
    email: "a.cherkaoui@um5.ac.ma",
    telephone: "06 44 55 66 77",
    linkedin: "linkedin.com/in/adam-cherkaoui",
    github: "github.com/adam-cherkaoui",
    bio: "Étudiant en Master Informatique, intéressé par les systèmes d'information RH.",
    ecole: "Université Mohammed V",
    filiere: "Master Informatique",
    typeStage: "PFE",
    departement: "Ressources Humaines",
    encadrantId: 4,
    encadrantName: "Hassan Oulhaj",
    dateDebut: "15 sept. 24",
    dateFin: "15 mars 25",
    avancement: 68,
    statut: "En cours",
    rapportStatut: "Non déposé",
    compteActif: false,
  },
  {
    id: 5,
    name: "Rania Mansouri",
    email: "r.mansouri@ensam.ac.ma",
    telephone: "06 55 66 77 88",
    bio: "Étudiante en Génie des Systèmes à l'ENSAM Casablanca.",
    ecole: "ENSAM Casablanca",
    filiere: "Génie des Systèmes",
    typeStage: "PFA",
    departement: "Opérations",
    encadrantId: null,
    encadrantName: null,
    dateDebut: "06 janv. 25",
    dateFin: "06 juin 25",
    avancement: 0,
    statut: "À venir",
    rapportStatut: "Non déposé",
    compteActif: true,
  },
  {
    id: 6,
    name: "Mehdi Fassi",
    email: "m.fassi@hec.ac.ma",
    telephone: "06 66 77 88 99",
    linkedin: "linkedin.com/in/mehdi-fassi",
    github: "github.com/mehdi-fassi",
    bio: "Étudiant en Master Data Science à HEC Paris, spécialisé en marketing analytics.",
    ecole: "HEC Paris",
    filiere: "Master Data Science",
    typeStage: "PFE",
    departement: "Marketing",
    encadrantId: 5,
    encadrantName: "Salma Tahiri",
    dateDebut: "01 juil. 24",
    dateFin: "01 nov. 24",
    avancement: 100,
    statut: "Terminé",
    rapportStatut: "Validé",
    rapportFichierNom: "rapport-stage-mehdi-fassi.pdf", // NOUVEAU — cas "Validé" pour tester ce statut aussi
    rapportDateDepot: "25 oct. 2024",
    compteActif: true,
  },
];